import type { NextPage } from "next";
import Head from "next/head";
import { Container, Content, Title } from "../styles/home";
import useSWR from "swr";
import Card from "../components/Card";
import { Environment } from "../Interfaces/Environemnts";

const fetcher = (...args: Parameters<typeof fetch>) =>
  fetch(...args).then((response) => response.json());

const Home: NextPage = () => {
  const url = `${process.env.ENDPOINT}/api/v1.0/environments`;
  const { data } = useSWR(url, fetcher);

  return (
    <>
      <Head>
        <title>Env Dash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>Environment Dashboard</Title>
        <Content>
          {data?.environments.map((env: Environment) => (
            <Card key={env.name} data={env} />
          ))}
        </Content>
      </Container>
    </>
  );
};

export default Home;
