import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Content } from '../styles/home';
import useSWR from 'swr';
import Accordion from '../components/Accordion';
import { Environment } from '../Interfaces/Environemnts';

const fetcher = (...args: Parameters<typeof fetch>) =>
  fetch(...args).then((response) => response.json());

const Home: NextPage = () => {
  const url = `${process.env.ENDPOINT}/api/v1.0/environments`;
  const { data } = useSWR(url, fetcher);

  return (
    <Container>
      <Head>
        <title>Env Dash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        {data?.environments.map((item: Environment) => (
          <Accordion key={item.name} name={item.name} state={item.state} />
        ))}
      </Content>
    </Container>
  );
};

export default Home;
