import type { NextPage } from 'next';
import Head from 'next/head';
import { Container } from '../styles/home';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Env Dash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      HELLO ENVIRONMENT DASHBOARD
    </Container>
  );
};

export default Home;
